name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.8'
    - name: Checkout
      uses: actions/checkout@master
    - name: Generate Report
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install coverage
        coverage run -m unittest discover
        coverage xml
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: false # optional (default = false)
